[package]
name = "depsy-zed"
version = "2.0.0"
edition = "2024"
rust-version = "1.90"
license = "MIT"
description = "Zed extension for dependency management"
authors = ["Mathieu"]

[lib]
crate-type = ["cdylib"]

[dependencies]
zed_extension_api = "0.7"
sha2 = "0.11"

[lints.clippy]
uninlined_format_args = "warn"
unnecessary_debug_formatting = "warn"
