source 'https://rubygems.org'

gem 'rails', '~> 7.0.0'
gem 'pg', '>= 1.1'
gem "puma", "~> 5.0"

group :development, :test do
  gem 'rspec-rails', '~> 6.0.0'
  gem 'debug'
end

group :development do
  gem 'rubocop', require: false
end
