//! Common utility functions used across the LSP implementation.

use core::fmt::{self, Write as _};

/// Returns an <code>[fmt::Display] + [fmt::Debug]</code> implementation
/// which truncates the given string to a maximum character count.
///
/// This function properly handles UTF-8 strings by counting characters,
/// not bytes. The truncation behavior depends on `max_chars`:
///
/// - **`max_chars >= 3`**: If the string exceeds `max_chars`, it is truncated
///   with an ellipsis (`"..."`). The total output length (including the ellipsis)
///   is exactly `max_chars`.
/// - **`max_chars < 3`**: The ellipsis cannot fit, so the string is simply
///   truncated to `max_chars` characters with no ellipsis appended.
/// - If the string already fits within `max_chars`, it is returned unchanged.
///
/// # Arguments
///
/// * `s` - The string to truncate
/// * `max_chars` - Maximum number of characters in the output
///
/// # Returns
///
/// The truncated string, or the original string if it fits within `max_chars`.
#[must_use = "returns a type implementing Display and Debug, which does not have any effects unless they are used"]
pub fn fmt_truncate_string(s: &str, max_chars: usize) -> impl fmt::Display + fmt::Debug {
    fmt::from_fn(move |f| {
        let char_count = s.chars().count();
        if char_count <= max_chars {
            return f.write_str(s);
        }

        // When max_chars < 3, we can't fit the ellipsis ("...")
        // so just truncate to max_chars characters
        if max_chars < 3 {
            return s.chars().take(max_chars).try_for_each(|c| f.write_char(c));
        }

        let keep_chars = max_chars.saturating_sub(3);
        s.chars()
            .take(keep_chars)
            .try_for_each(|c| f.write_char(c))?;
        write!(f, "...")
    })
}

/// Escape HTML special characters for safe embedding in HTML text content
/// and double-quoted attribute values.
///
/// Handles `&`, `<`, `>`, `"`, and `'` — the five characters that can break
/// out of text content or attribute values. Suitable for any position inside
/// a static HTML template generated by string concatenation.
///
/// # Arguments
///
/// * `s` - The input string to escape
///
/// # Returns
///
/// A new `String` with unsafe characters replaced by their HTML entities.
///
/// # Allocation
///
/// Pre-allocates at least `s.len()` bytes. Grows only if escaping expands the
/// output (i.e. if any of the five special characters appear).
#[must_use = "returns the escaped string; the original is not modified"]
pub fn html_escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            _ => out.push(c),
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn truncate_string(s: &str, max_chars: usize) -> String {
        fmt_truncate_string(s, max_chars).to_string()
    }

    #[test]
    fn test_no_truncation_needed() {
        assert_eq!(truncate_string("hello", 10), "hello");
        assert_eq!(truncate_string("", 10), "");
        assert_eq!(truncate_string("hello", 5), "hello");
    }

    #[test]
    fn test_ascii_truncation() {
        assert_eq!(truncate_string("hello world", 8), "hello...");
        assert_eq!(truncate_string("abcdefghij", 7), "abcd...");
    }

    #[test]
    fn test_edge_cases() {
        assert_eq!(truncate_string("hello", 3), "..."); // Exactly 3: ellipsis fits
        assert_eq!(truncate_string("hello", 4), "h...");
    }

    #[test]
    fn test_small_max_chars() {
        // max_chars < 3: truncate without ellipsis
        assert_eq!(truncate_string("hello", 2), "he");
        assert_eq!(truncate_string("ab", 1), "a");
        assert_eq!(truncate_string("a", 0), "");
        assert_eq!(truncate_string("hello world", 1), "h");
    }

    #[test]
    fn test_utf8_japanese() {
        // "日本語" = 3 characters, 9 bytes
        assert_eq!(truncate_string("日本語", 10), "日本語");
        assert_eq!(truncate_string("日本語", 3), "日本語");
        // "日本語test" = 7 characters
        // truncate to 6 means keep 3 + "..." = 6 total
        assert_eq!(truncate_string("日本語test", 6), "日本語...");
        // 7 chars <= 8, so no truncation needed
        assert_eq!(truncate_string("日本語test", 8), "日本語test");
        // 7 chars <= 7, so no truncation needed
        assert_eq!(truncate_string("日本語test", 7), "日本語test");
        // truncate to 5 means keep 2 + "..." = 5
        assert_eq!(truncate_string("日本語test", 5), "日本...");
    }

    #[test]
    fn test_utf8_emoji() {
        // "hello" = 5 characters, fits in 8
        assert_eq!(truncate_string("hello", 8), "hello");
        // "hello world" = 11 characters, truncate to 8 means keep 5 + "..."
        let emoji_str = "hello world";
        assert_eq!(truncate_string(emoji_str, 8), "hello...");
    }

    #[test]
    fn test_mixed_content() {
        assert_eq!(truncate_string("Hello 日本", 10), "Hello 日本");
        assert_eq!(truncate_string("Hello 日本語 world", 12), "Hello 日本語...");
    }

    #[test]
    fn test_html_escape_basic() {
        assert_eq!(html_escape("a&b"), "a&amp;b");
        assert_eq!(html_escape("<tag>"), "&lt;tag&gt;");
        assert_eq!(html_escape(r#"say "hi""#), "say &quot;hi&quot;");
        assert_eq!(html_escape("it's"), "it&#39;s");
        assert_eq!(
            html_escape(r#"<script>alert("x")</script>"#),
            "&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;"
        );
    }

    #[test]
    fn test_html_escape_all_special_chars() {
        assert_eq!(html_escape("&<>\"'"), "&amp;&lt;&gt;&quot;&#39;");
    }

    #[test]
    fn test_html_escape_passthrough() {
        assert_eq!(html_escape(""), "");
        assert_eq!(html_escape("hello 123"), "hello 123");
        assert_eq!(html_escape("éàü日本"), "éàü日本");
    }

    #[test]
    fn test_html_escape_idempotent_on_safe_text() {
        let safe = "plain text with digits 42 and unicode é";
        assert_eq!(html_escape(safe), safe);
    }
}
